[package]
name = "moon_pdk"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A plugin development kit for creating moon WASM plugins."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"

[dependencies]
moon_pdk_api = { version = "0.0.1", path = "../pdk-api" }
extism-pdk = { workspace = true }
serde = { workspace = true }
warpgate_api = { workspace = true, features = ["pdk"] }
