[workspace]
resolver = "2"
members = [
	"crates/cli",
	"crates/core/*",

	# Languages
	"crates/bun/*",
	"crates/deno/*",
	"crates/javascript/*",
	"crates/node/*",
	"crates/rust/*",
	"crates/system/*",
	"crates/typescript/*",

	# Next-gen
	"nextgen/*",
]
exclude = ["tests/fixtures"]
default-members = ["crates/cli"]

[workspace.dependencies]
async-trait = "0.1.77"
cached = "0.47.0"
chrono = { version = "0.4.31", features = ["serde"] }
cd_env = "0.1.2"
ci_env = "0.2.1"
clap = { version = "4.4.16", features = ["derive", "env", "wrap_help"] }
clap_complete = "4.4.6"
console = "0.15.7"
dirs = "5.0.1"
extism = "1.0.0"
extism-pdk = "1.0.0"
miette = "5.10.0"
once_cell = "1.19.0"
once_map = "0.4.14"
pathdiff = "0.2.1"
petgraph = { version = "0.6.4", default-features = false, features = [
	"serde-1",
] }
relative-path = { version = "1.9.2", features = ["serde"] }
regex = "1.10.2"
reqwest = { version = "0.11.23", default-features = false, features = [
	"rustls-tls-native-roots",
	# We don't use openssl but its required for musl builds
	"native-tls-vendored",
] }
rustc-hash = "1.1.0"
schematic = { version = "0.13.5", default-features = false, features = [
	"config",
	"schema",
	"url",
	"yaml",
	"type_semver",
] }
semver = "1.0.21"
serde = { version = "1.0.195", features = ["derive", "rc"] }
serde_json = "1.0.111"
serde_yaml = "0.9.30"
starbase = "0.2.13"
starbase_archive = { version = "0.2.5", default-features = false, features = [
	"tar-gz",
] }
starbase_events = "0.2.2"
starbase_sandbox = "0.1.13"
starbase_styles = { version = "0.1.17", features = ["relative-path"] }
starbase_utils = { version = "0.3.11", default-features = false, features = [
	"editor-config",
	"glob",
	"json",
	"toml",
	"yaml",
] }
tera = { version = "1.19.1", features = ["preserve_order"] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", default-features = false, features = [
	"macros",
	"process",
	"rt-multi-thread",
	"rt",
	"signal",
	"time",
	"tracing",
] }
tokio-util = "0.7.10"
tracing = "0.1.40"
url = "2.5.0"
uuid = { version = "1.6.1", features = ["v4"] }

# proto related
proto_core = { version = "0.28.4", path = "../proto/crates/core" }
proto_installer = "0.2.0"
proto_pdk = { version = "0.14.3", path = "../proto/crates/pdk" }
system_env = { version = "0.2.0", path = "../proto/crates/system-env" }
warpgate = { version = "0.9.2", path = "../proto/crates/warpgate" }
warpgate_api = { version = "0.2.0", path = "../proto/crates/warpgate-api" }
