[package]
name = "moon_tool"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
moon_common = { path = "../../../nextgen/common" }
moon_lang = { path = "../lang" }
moon_platform_runtime = { path = "../../../nextgen/platform-runtime" }
moon_process = { path = "../../../nextgen/process" }
async-trait = { workspace = true }
miette = { workspace = true }
proto_core = { workspace = true }
rustc-hash = { workspace = true }
starbase_styles = { workspace = true }
thiserror = { workspace = true }
warpgate = { workspace = true }
